# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('summary', models.CharField(default='No Sumaary', max_length=200)),
                ('tags', models.CharField(default='未分类', max_length=200)),
                ('img', models.ImageField(default='', upload_to='')),
                ('create_time', models.DateField(default='2012-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('url', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
    ]
