# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.IntegerField(default=0, verbose_name='people who views'),
        ),
    ]
